source 'https://rubygems.org'

gem 'rails', '~> 7.1.3'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.0'
gem 'rack-cors'
gem 'jwt'
gem 'active_model_serializers', '~> 0.10.13'

group :development do
  gem 'listen', '~> 3.8'
end

group :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails', '~> 6.2'
end
